server:
  port: 7901
user:
  userServicePath: http://localhost:7900/user/
logging:
  level:
    root: INFO
    org.hibernate: INFO
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.hibernate.type.descriptor.sql.BasicExtractor: TRACE
    com.huaxin: DEBUG
spring:
  application:
    name: micorservice-consumer-movie
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://diaoby:diaoby@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}