server:
  port: 7902
user:
  userServicePath: http://microservice-provider-user/
spring:
  application:
    name: micorservice-consumer-movie-ribbon
#eureka
eureka:
  client:
    service-url:
      defaultZone: http://diaoby:diaoby@localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${server.port}}